language: objective-c
osx_image: xcode7.1
env:
  global:
  - PROJECT=SwiftyAcknowledgements.xcodeproj
  - IOS_FRAMEWORK_SCHEME="SwiftyAcknowledgements iOS"
  - TVOS_FRAMEWORK_SCHEME="SwiftyAcknowledgements tvOS"
  - IOS_SDK=iphonesimulator9.1
  - TVOS_SDK=appletvsimulator9.0
  - IOS_EXAMPLE_SCHEME="iOS Example"
  - TVOS_EXAMPLE_SCHEME="tvOS Example"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=8.2,name=iPhone 5"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=8.3,name=iPhone 5S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=8.4,name=iPhone 6"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=9.1,name=iPhone 6S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"   BUILD_EXAMPLE="YES"   EXAMPLE_SCHEME="$TVOS_EXAMPLE_SCHEME"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Build Example in Release if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
